[project]
name = "dfm-research-paper-digest"
version = "2026.05.11"
description = "Create a report of PubMed articles by DFM faculty."
readme = "README.md"
authors = [
    {name = "Mihir Jagtap", email = "<jagtapmihir4@gmail.com>"},
    {name = "Kevin J. Delaney", email = "<kjdelaney@health.ucsd.edu>"},
]
requires-python = ">=3.12"
dependencies = [
    "auto-mix-prep==0.2.0",
    "beautifulsoup4==4.15.0",
    "metapub==0.7.5",
    "nameparser==2.3.0",
    "requests==2.34.2",
    "streamlit==1.64.0",
    "typing-extensions==4.16.0",
]

[project.urls]
documentation = "https://github.com/UCSD-Tai-Seale-Lab/DFM-Research-Paper-Digest"
homepage = "https://github.com/UCSD-Tai-Seale-Lab/DFM-Research-Paper-Digest"
repository = "https://github.com/UCSD-Tai-Seale-Lab/DFM-Research-Paper-Digest"

[tool.poetry.group.dev.dependencies]
make = "*"
mkdocs = "*"
mkdocstrings = "*"
mkdocs-material = "*"
openpyxl = "*"
pep8-naming = "*"
pre-commit = "*"
pymdown-extensions = "*"
pytest = "*"
pytest-github-actions-annotate-failures = "*"
pytest-cov = "*"
python-kacl = "*"
pyupgrade = "*"
ruff = "*"
setuptools = "<82"
wheel = "*"
