import logging
from pathlib import Path

import bs4
from metapub import PubMedAuthor

from src.dfm_research_paper_digest.author import Author  # pylint: disable=import-error

class Faculty:
    __list: list[Author] = None
    __log: logging.Logger = None
    authors: list[Author] = None
    names: list[str] = None
    num: int = None

    # Can create from existing hard-coded list, a filename or a Path object.
    def __init__(self, faculty_list: list[str] | str | Path, log: logging.Logger): ...
    def __extract_dbmi_names(self, soup: bs4.BeautifulSoup) -> list[str]: ...
    def __extract_dfm_names(self, soup: bs4.BeautifulSoup) -> list[str]: ...
    def is_faculty(self, author: Author | PubMedAuthor | str) -> bool: ...
    def __is_url(self, name: str | Path) -> bool: ...
    def __names(self) -> list[str]: ...
    def __original_names(self) -> list[str]: ...
    def __read_faculty_list_file(self, file: str | Path) -> list[str]: ...
    def __scrape_webpage(self, site_address: str) -> list[str]: ...
