# https://share.google/aimode/WtAUTFLxlLqbopKoh
name: Keep Workflows Alive

on:
  schedule:
    # Runs at 01:03 on day 1 of every month
    - cron: "3 1 1 * *"
  # Allows you to also trigger this manually from the Actions tab
  workflow_dispatch:

jobs:
    workflow-keepalive:
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        permissions:
          actions: write
        steps:
          - uses: liskin/gh-workflow-keepalive@v1
